name : CI

on: [push,workflow_dispatch]

jobs:
build:

runs-on: windows=latest

steps:
- name: Download
run: Invoke-WebRequest http://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-windows-amd64.zip -Outfile ngrok.zip
- name: Extract
run: Expand-Archive ngrok.zip
- name: Auth
run: .\ngrok\ngrok.exe authtoken $Env:NGROK_AUTH_TOKEN
env:
      NGROK_AUTH_TOKEN: ${{ secret.NGROK_AUTH_TOKEN}}
- name: Enable TS
run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name "FDenyTSConnections" -Value 0
- run: Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
- run: set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
- run: set-LocalUser Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText "P@ssword!" -Force) 
- name: Create Tunnel
run: .\ngrok\ngrok.exe tcp 3389
